// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_KeGydE1XBNxV1Ts3JsiGbnPY6AHDaqM',
    appId: '1:10972751751:android:20042324bd4704f4ead522',
    messagingSenderId: '10972751751',
    projectId: 'imis-d55f4',
    databaseURL: 'https://imis-d55f4.firebaseio.com',
    storageBucket: 'imis-d55f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPAx2O_bq0KLolfAZKHxhHu7b0C0u4I-Y',
    appId: '1:10972751751:ios:280096465582729fead522',
    messagingSenderId: '10972751751',
    projectId: 'imis-d55f4',
    databaseURL: 'https://imis-d55f4.firebaseio.com',
    storageBucket: 'imis-d55f4.appspot.com',
    iosClientId: '10972751751-81v8rr5iog3gbnboia7shgi99cqg0hkt.apps.googleusercontent.com',
    iosBundleId: 'imis.nictanzania.co.imisClientApp.ios.release',
  );
}
